
export class Producto {
    constructor(
        public ID_PRODUCTO?: number,
        public COD_PRODUCTO?: string,
        public COD_BARRAS?: string,
        public _id?: string,
        public COD_CORTO?: string,
        public NOMBRE?: string,
        public CARACTERISTICAS?: string,
        public UNIDAD_MEDIDA?: string,
        public KILO_BOLSA?: string,
        public ULT_PREC_COMPRA?: string,
        public ULT_PREC_VENNTA?: string,
        public STOCK?: string,
        public IVA_GRAVADO?: string,
        public IVA_EXCENTA?: string,
        public IVA_INCLUIDO?: string,
        public IVA_5?: string,
        public IVA_10?: string,
        public TIENE_MEZCLA?: string,
        public FECHA_ULT_COMPRA?: string,
        public FECHA_ULT_VENTA?: string,
        public ID_FAMILIA?: string,
        public NOMBRE_FAMILIA?: string,
        public COD_UBICACION?: string,
        public STOCK_MINIMO?: string,
        public STOCK_COMPRA?: string,
        public STOCK_MAXIMO?: string,
        public FECHA_ALTA?: string,
        public DESCUENTO?: string,
        public COD_TIPO?: string,
        public COD_MONEDA?: string,
        public COMENTARIO?: string,
        public MARGEN_GANAN?: string,
        public COD_DEPOSITO?: string,
        public CTA_CBLE_VENTA?: string,
        public CTA_CTBLE_COMP?: string,
        public CTA_CTBLE_PRES?: string,
        public DIRE_IMAGEN?: string,
        public proveedor1?: string,
        public proveedor2?: string,
        public proveedor3?: string,
        public PRECIO_MINORISTA?: number,
        public PRECIO_MAYORISTA?: number,
        public PRECIO_COMPRA?: number,
        public SERVICIO?: string,
        public PRODUCTO?: string,
        public MANZANA?: string, 
    ) {

    }
}