


export class Usuario {
    constructor(

        public id_cliente: string,
        public APELLIDOS: string,
        public _id: string,
        public NOMBRES: string,
        public RAZON: string,
        public RUC: string,
        public DIRECCION: string,
        public LUGAR_TRABAJO: string,
        public TEL_TRABAJO: string,
        public NOMCIUDAD: string,
        public NOMDEPAR: string,
        public CARGOCONTA: string,
        public TELEFONO: string,
        public TELEFONO_FAX: string,
        public NOTAS: string,
        public DIAS_VENCI: string,
        public PLAZOS_CREDITO: string,
        public LINEA_CREDITO: string,
        public HABILITADO: string,
        public SALDO: string,
        public ULTIMO_PAGO: string,
        public ID_LISTA: string,
        public CAMBIA_VEN: string,
        public NOMBRE_LISTA: string,
        public PORCENTAJE: string,
        public NOMBRE_CONTACTO: string,
        public CARGO_CONT: string,
        public TEL_CONTACTO: string,
        public NOMBRE_CO2: string,
        public CARGO_CON2: string,
        public TEL_CONTA2: string,
        public NOMBRE_CO3: string,
        public CARGO_CON3: string,
        public TEL_CONTA3: string,
        public NOMBRE_CO4: string,
        public CARGO_CON4: string,
        public TEL_CONTA4: string,
        public CARGO_CON5: string,
        public TEL_CONTA5: string,
        public NOTAS1: string,
        public NOTAS2: string,
        public MORATORIO: string,
        public NUEVO: string,
        public ACTIVO: string,
        public ID_COBRADOR: string,
        public NOMBRE_COBRADOR: string,
        public ID_VENDEDOR: string,
        public NOMBRE_VENDEDOR: string,
        public DIRECCION_TRABAJO: string,
        public ID_BENEFICIACIO: string,
        public TIPO_FICHA: string,
        public TELEFONO1: string,
        public TELEFONO2: string,
        public TELEFONO3: string,
        public EMAIL: string,
        public CLIENTES: string,
        public PROVEEDORES: string,
        public VENDEDORES: string,
        public EMPLEADOS: string,
        public PERSONA: string,
        public EMPRESA: string,
        public BANCOS: string,
        public MANEJA_CAJA: string,
        public COBRADORES: string,
        public nro_inicial: string,
        public nro_final: string,
        public direccion_particular: string,
        public direccion_laboral: string,
        public fecha_alta: string,
        public ciudad_trabajo: string,
    ) {

    }
}
